name: HetimaTorrentFile
description: A sample Chrome packaged application
dependencies:
  chrome: any
  dart_web_toolkit: any
  hetimacore:
    path: ../../../dart_hetimacore
  hetimanet:
    path: ../../../dart_hetimanet
  hetimatorrent:
    path: ../../
transformers:
- chrome
- $dart2js:
    csp: true
